# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: us-east-2
        role-to-assume: arn:aws:iam::154804583687:user/udacityuser
        role-session-name: udacityuser
        
    - uses: iterative/setup-dvc@v1    
    - name: DVC pull
      run: |
        dvc pull --remote myremote
  
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install scikit-learn pandas numpy pytest jupyter jupyterlab fastapi flake8 xgboost
        
    - name: Lint with flake8
      run: |
        flake8 --ignore=E501,E402,E226,E231 .
   
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: us-east-2
        role-to-assume: arn:aws:iam::154804583687:user/udacityuser
        role-session-name: udacityuser
    - name: Test with pytest
      run: |
        pytest





